### ISSUE TITLE
Implement array-filter-sort-map

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/array-filter-sort-map#1]
<img width="900" alt="22-array-filter-sort-map" src="https://github.com/user-attachments/assets/07ea0e3b-9d8c-4597-9157-9013509746cb">

**Comment by kimiaRahimi** [comment]
سلام وقتتون بخیر . این تسک منظورش از highest ranking چیه؟

**Comment by kimiaRahimi** [comment]
@FarshadJanmohammadi

**Comment by FarshadJanmohammadi** [comment]
> سلام وقتتون بخیر . این تسک منظورش از highest ranking چیه؟

سلام، توی ورودی یه ارایه ای از ابجکت ها میگیره، که هر ابجکت اسم دانش اموز و نمره اون قرار داره، حالا باید سورت کنی بر اساس بالاترین نمره و توی خروجی باید فقط اسم رو توی ارایه برگردونی، یعنی در نهایت اون ارایه ای از ایجکت ها تبدیل میشه به ارایه ای از استرینگ ها ، که هر استرینگ نام دانش اموزه که سورت شده بر اساس بالاترین نمره
